REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\mre_miniz_tools\mre_miniz_tools.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_miniz_tools\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_miniz_tools\include" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\include\component" -I "D:\MyGitHub\mre_miniz_tools\ResID" -I "D:\MyGitHub\mre_miniz_tools\src\app\widget" -I "D:\MyGitHub\mre_miniz_tools\src\app\launcher" -I "D:\MyGitHub\mre_miniz_tools\src\app\wallpaper" -I "D:\MyGitHub\mre_miniz_tools\src\app\screen_lock" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\include\component" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\src\framework" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\base" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_miniz_tools\src\framework\mmi_core" -I "D:\MyGitHub\mre_miniz_tools\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_miniz_tools\src\component" -I "D:\MyGitHub\mre_miniz_tools\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_miniz_tools"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_miniz_tools\arm\mre_miniz_tools.o" -c "d:\MyGitHub\mre_miniz_tools\mre_miniz_tools.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_miniz_tools\include" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\include\component" -I "D:\MyGitHub\mre_miniz_tools\ResID" -I "D:\MyGitHub\mre_miniz_tools\src\app\widget" -I "D:\MyGitHub\mre_miniz_tools\src\app\launcher" -I "D:\MyGitHub\mre_miniz_tools\src\app\wallpaper" -I "D:\MyGitHub\mre_miniz_tools\src\app\screen_lock" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\include\component" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\src\framework" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\base" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_miniz_tools\src\framework\mmi_core" -I "D:\MyGitHub\mre_miniz_tools\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_miniz_tools\src\component" -I "D:\MyGitHub\mre_miniz_tools\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_miniz_tools"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_miniz_tools\arm\mre_stdlibio.o" -c "d:\MyGitHub\mre_miniz_tools\mre_stdlibio.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_miniz_tools\include" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\include\component" -I "D:\MyGitHub\mre_miniz_tools\ResID" -I "D:\MyGitHub\mre_miniz_tools\src\app\widget" -I "D:\MyGitHub\mre_miniz_tools\src\app\launcher" -I "D:\MyGitHub\mre_miniz_tools\src\app\wallpaper" -I "D:\MyGitHub\mre_miniz_tools\src\app\screen_lock" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\include\component" -I "D:\MyGitHub\mre_miniz_tools\include\service" -I "D:\MyGitHub\mre_miniz_tools\src\framework" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\base" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_miniz_tools\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_miniz_tools\src\framework\mmi_core" -I "D:\MyGitHub\mre_miniz_tools\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_miniz_tools\src\component" -I "D:\MyGitHub\mre_miniz_tools\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_miniz_tools"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\mre_miniz_tools\mre_miniz_tools.axf"  "D:\MyGitHub\mre_miniz_tools\arm\gccmain.o"  "D:\MyGitHub\mre_miniz_tools\arm\mre_miniz_tools.o"  "D:\MyGitHub\mre_miniz_tools\arm\mre_stdlibio.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\mre_miniz_tools\mre_miniz_tools.pkd" -e AXF "D:\MyGitHub\mre_miniz_tools\mre_miniz_tools.vcproj" "D:\MyGitHub\mre_miniz_tools\mre_miniz_tools.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\mre_miniz_tools\mre_miniz_tools.vcproj" "mre_miniz_tools" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "mre_miniz_tools" "mre_miniz_tools" "mre_miniz_tools" "1234567890" "content" " File SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\mre_miniz_tools\arm D:\MyGitHub\mre_miniz_tools\build.log

